"""eml_id 크기 변경

Revision ID: ff18525f7cc1
Revises: 2d4657d8a54f
Create Date: 2024-04-30 14:42:13.036319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff18525f7cc1'
down_revision: Union[str, None] = '2d4657d8a54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('com_user_email_auth')
    op.drop_index('eml_id', table_name='eml_mail_info')
    op.drop_table('eml_mail_info')
    op.drop_table('eml_attachment_info')
    op.drop_index('key', table_name='sys_config')
    op.drop_table('sys_config')
    op.drop_index('user_id', table_name='com_user_info')
    op.drop_table('com_user_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('com_user_info',
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'com_user_info', ['user_id'], unique=True)
    op.create_table('sys_config',
    sa.Column('key', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('key', 'sys_config', ['key'], unique=True)
    op.create_table('eml_attachment_info',
    sa.Column('attach_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('eml_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_size', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('content_type', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('attach_id', 'eml_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('eml_mail_info',
    sa.Column('eml_id', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('eml_box', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('eml_from', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('eml_sender', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('eml_to', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('eml_subject', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('eml_content', mysql.TEXT(), nullable=False),
    sa.Column('received_at', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('eml_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('eml_id', 'eml_mail_info', ['eml_id'], unique=True)
    op.create_table('com_user_email_auth',
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['com_user_info.user_id'], name='com_user_email_auth_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
